name: skuterlar_shop
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6

  #family style
  google_fonts: ^6.2.1

  #statemanagment
  flutter_riverpod: ^2.5.1

  #search for part
  flutter_typeahead: ^5.2.0

  #carousel for banner
  carousel_slider: ^4.2.1

  # for svgImage 
  flutter_svg: ^2.0.10+1

  #
  popover: ^0.3.0

  #format text
  flutter_multi_formatter: ^2.12.8

  # responsibility
  flutter_screenutil: ^5.9.0

  # for seamless localization management.
  easy_localization: ^3.0.7

  http: ^1.2.1
  #for locale store
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3

  http_interceptor: ^2.0.0-beta.8

  l: ^4.0.2
  package_info_plus: ^8.0.0

  




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/icons/chat/
    - assets/icons/product_icons/
    - assets/icons/home/
    - assets/icons/detail_page/
    - assets/images/savat/
    - assets/images/profile/
    - assets/icons/profile/
    - assets/icons/cart/
    - assets/icons/login/
    - assets/translations/



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
