import 'package:flutter/material.dart' show ColorScheme, Brightness, Color;
import 'package:skuterlar_shop/src/core/style/colors.dart';


 ColorScheme lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: AppColors.color_0157BE,
  onPrimary: AppColors.color_1E1E1E,
  primaryContainer: AppColors.color_EEEEEE,
  onPrimaryContainer: const Color(0xff141311),
  secondary: AppColors.color_0157BE,
  onSecondary: AppColors.color_EEEEEE,
  secondaryContainer: const Color(0xffffffff),
  onSecondaryContainer: const Color(0xff141414),
  tertiary: AppColors.color_C3C3C3,
  onTertiary: const Color(0xff000000),
  tertiaryContainer: const Color(0xffEDEDED),
  onTertiaryContainer: const Color(0xff141413),
  error: const Color(0xffb00020),
  onError: const Color(0xffffffff),
  errorContainer: const Color(0xfffcd8df),
  onErrorContainer: const Color(0xff141213),
  background: const Color.fromARGB(255, 253, 247, 243),
  onBackground: const Color(0xff0a0909),
  surface: const Color(0xfffffbf9),
  onSurface: AppColors.color_C3C3C3,
  surfaceVariant: const Color(0xffeee8e3),
  onSurfaceVariant: const Color(0xff121211),
  outline: const Color(0xff837676),
  outlineVariant: const Color(0xffccc6c6),
  shadow: const Color(0xff000000),
  scrim: const Color(0xff000000),
  inverseSurface: const Color(0xff171411),
  onInverseSurface: const Color(0xfff5f5f5),
  inversePrimary: const Color(0xfffff8c0),
  surfaceTint: const Color(0xff3F3F3F),
);

 ColorScheme darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: const Color(0xff6C7882),
  onPrimary: AppColors.color_FBFDFF,
  primaryContainer: AppColors.color_D9D9D9,
  onPrimaryContainer: const Color(0xffe9ecf1),
  secondary: const Color(0xff5EB4F6),
  onSecondary: const Color(0xff141210),
  secondaryContainer: const Color(0xff6C7882),
  onSecondaryContainer: const Color(0xfff3e6e2),
  tertiary: AppColors.color_EEEEEE,
  onTertiary: const Color(0xff131414),
  tertiaryContainer: const Color(0xff6C7882),
  onTertiaryContainer: const Color(0xffeaf7fb),
  error: const Color(0xffcf6679),
  onError: const Color(0xff140c0d),
  errorContainer: const Color(0xffb1384e),
  onErrorContainer: const Color(0xfffbe8ec),
  background: const Color(0xff17212B),
  onBackground: const Color(0xffeceded),
  surface: const Color(0xff181a1d),
  onSurface: const Color(0xffeceded),
  surfaceVariant: const Color(0xff3d4146),
  onSurfaceVariant: const Color(0xffe0e1e1),
  outline: const Color(0xff767d7d),
  outlineVariant: const Color(0xff2c2e2e),
  shadow: const Color(0xff000000),
  scrim: const Color(0xff000000),
  inverseSurface: const Color(0xfffafcff),
  onInverseSurface: const Color(0xff131314),
  inversePrimary: const Color(0xff536577),
  surfaceTint: const Color(0xffffffff),
);
